config/routes.rb
Accs::Application.routes.draw do
  resources :items

  resources :sections

  resources :curriculums

  resources :curriculum_assessments

  resources :dops

  resources :assessments

  devise_for :users

  resources :users
  root :to => "home#index"

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  attr_accessible :assessment_description, :assessment_title, :assessment_type, :assessor_email, :assessor_firstname, :assessor_gmc, :assessor_grade, :assessor_lastname, :assessor_name, :date
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assessments }
    end
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/new
  # GET /assessments/new.json
  def new
    @assessment = Assessment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/1/edit
  def edit
    @assessment = Assessment.find(params[:id])
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(params[:assessment])

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render json: @assessment, status: :created, location: @assessment }
      else
        format.html { render action: "new" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assessments/1
  # PUT /assessments/1.json
  def update
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      if @assessment.update_attributes(params[:assessment])
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy

    respond_to do |format|
      format.html { redirect_to assessments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.haml
= simple_form_for(@assessment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :assessor_email
    = f.input :assessment_type
    = f.input :date
    = f.input :assessor_name
    = f.input :assessor_grade
    = f.input :assessor_gmc
    = f.input :assessment_title
    = f.input :assessment_description
    = f.input :assessor_firstname
    = f.input :assessor_lastname

  .form-actions
    = f.button :submit

app/views/assessments/edit.html.haml
%h1 Editing assessment

= render 'form'

= link_to 'Show', @assessment
\|
= link_to 'Back', assessments_path

app/views/assessments/index.html.haml
%h1 Listing assessments

%table
  %tr
    %th Assessor email
    %th Assessment type
    %th Date
    %th Assessor name
    %th Assessor grade
    %th Assessor gmc
    %th Assessment title
    %th Assessment description
    %th Assessor firstname
    %th Assessor lastname
    %th
    %th
    %th

  - @assessments.each do |assessment|
    %tr
      %td= assessment.assessor_email
      %td= assessment.assessment_type
      %td= assessment.date
      %td= assessment.assessor_name
      %td= assessment.assessor_grade
      %td= assessment.assessor_gmc
      %td= assessment.assessment_title
      %td= assessment.assessment_description
      %td= assessment.assessor_firstname
      %td= assessment.assessor_lastname
      %td= link_to 'Show', assessment
      %td= link_to 'Edit', edit_assessment_path(assessment)
      %td= link_to 'Destroy', assessment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Assessment', new_assessment_path

app/views/assessments/new.html.haml
%h1 New assessment

= render 'form'

= link_to 'Back', assessments_path

app/views/assessments/show.html.haml
%p#notice= notice

%p
  %b Assessor email:
  = @assessment.assessor_email
%p
  %b Assessment type:
  = @assessment.assessment_type
%p
  %b Date:
  = @assessment.date
%p
  %b Assessor name:
  = @assessment.assessor_name
%p
  %b Assessor grade:
  = @assessment.assessor_grade
%p
  %b Assessor gmc:
  = @assessment.assessor_gmc
%p
  %b Assessment title:
  = @assessment.assessment_title
%p
  %b Assessment description:
  = @assessment.assessment_description
%p
  %b Assessor firstname:
  = @assessment.assessor_firstname
%p
  %b Assessor lastname:
  = @assessment.assessor_lastname

= link_to 'Edit', edit_assessment_path(@assessment)
\|
= link_to 'Back', assessments_path