config/routes.rb
Accs::Application.routes.draw do
  resources :items

  resources :sections

  resources :curriculums

  resources :curriculum_assessments

  resources :dops

  resources :assessments

  devise_for :users

  resources :users
  root :to => "home#index"

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  attr_accessible :name, :year, :section_ids
  has_many :sections
  has_many :items, through: :sections
end

app/models/dop.rb
class Dop < ActiveRecord::Base
  attr_accessible :analalgesia, :aseptic, :assesser_GMC, :assessor, :assessor_contact, :assessor_email, :assessor_postion, :clinical_encouter, :clinical_setting, :communication, :complexity, :consent, :consideration, :number_previous_assessor, :number_previous_trainee, :overall, :post_procedure, :preparation, :problem_category, :seeks_help, :suggestions, :technical_ability, :time_feedback, :time_observation, :training, :understanding, :item_ids, :item_id
  belongs_to :user
  has_many :items, through: :curriculum_assessments
  has_many :curriculum_assessments
end

app/controllers/dops_controller.rb
class DopsController < ApplicationController
  # GET /dops
  # GET /dops.json
  def index
    @dops = Dop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dops }
    end
  end

  # GET /dops/1
  # GET /dops/1.json
  def show
    @dop = Dop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dop }
    end
  end

  # GET /dops/new
  # GET /dops/new.json
  def new
    @dop = Dop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dop }
    end
  end

  # GET /dops/1/edit
  def edit
    @dop = Dop.find(params[:id])
  end

  # POST /dops
  # POST /dops.json
  def create
    @dop = current_user.dops.new(params[:id])

    respond_to do |format|
      if @dop.save
        format.html { redirect_to @dop, notice: 'Dop was successfully created.' }
        format.json { render json: @dop, status: :created, location: @dop }
      else
        format.html { render action: "new" }
        format.json { render json: @dop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dops/1
  # PUT /dops/1.json
  def update
    @dop = Dop.find(params[:id])

    respond_to do |format|
      if @dop.update_attributes(params[:dop])
        format.html { redirect_to @dop, notice: 'Dop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dops/1
  # DELETE /dops/1.json
  def destroy
    @dop = Dop.find(params[:id])
    @dop.destroy

    respond_to do |format|
      format.html { redirect_to dops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/do_ps_helper.rb
module DoPsHelper
end

app/views/dops/_form.html.haml
= form_for(@dop) do |f| 
  
  .field

    = f.label :item_ids, "items"
    = f.collection_select :item_ids, Item.order(:name), :id, :name, {}, {multiple: true} 
  
  .actions
    = f.submit 


= simple_form_for(@dop, :html => { :class => 'form-horizontal' }) do |f|
  /= f.error_notification
    
  .form-inputs
   
    /= f.association :items, as: :check_boxes

    = f.input :clinical_setting,  collection: [ "A&E", "Clinic", "Ward", "Acute Admission"], as: :radio_buttons, item_wrapper_class: 'inline'
    = f.input :problem_category
    = f.input :clinical_encouter
    = f.input :complexity
    = f.input :assessor_postion
    = f.input :number_previous_assessor
    = f.input :number_previous_trainee
    
    %table.table.table-bordered.table-striped.table-hover  

      %tr
        %th Unable to Comment
        %th Below Expectations 
        %th Bordeline
        %th Meets Expectations
        %th Above Expectations
        %th Totally Exceeds Expectations

      

        = f.input :understanding, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :consent, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :preparation, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :analalgesia, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :technical_ability, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :aseptic, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :seeks_help, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :post_procedure, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :communication, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :consideration, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :overall, collection: 0..5, as: :radio_buttons, item_wrapper_class: 'inline'
        = f.input :suggestions
        = f.input :training
        = f.input :time_observation
        = f.input :time_feedback
        = f.input :assessor
        = f.input :assesser_GMC
        = f.input :assessor_contact
        = f.input :assessor_email

  .form-actions
    = f.button :submit

app/views/dops/edit.html.haml
%h1 Editing dop

= render 'form'

= link_to 'Show', @dop
\|
= link_to 'Back', dops_path

app/views/dops/index.html.haml
%h1 Listing dops

%table
  %tr
    %th Clinical setting
    %th Problem category
    %th Clinical encouter
    %th Complexity
    %th Assessor postion
    %th Number previous assessor
    %th Number previous trainee
    %th Understanding
    %th Consent
    %th Preparation
    %th Analalgesia
    %th Technical ability
    %th Aseptic
    %th Seeks help
    %th Post procedure
    %th Communication
    %th Consideration
    %th Overall
    %th Suggestions
    %th Training
    %th Time observation
    %th Time feedback
    %th Assessor
    %th Assesser gmc
    %th Assessor contact
    %th Assessor email
    %th
    %th
    %th

  - @dops.each do |dop|
    %tr
      %td= dop.clinical_setting
      %td= dop.problem_category
      %td= dop.clinical_encouter
      %td= dop.complexity
      %td= dop.assessor_postion
      %td= dop.number_previous_assessor
      %td= dop.number_previous_trainee
      %td= dop.understanding
      %td= dop.consent
      %td= dop.preparation
      %td= dop.analalgesia
      %td= dop.technical_ability
      %td= dop.aseptic
      %td= dop.seeks_help
      %td= dop.post_procedure
      %td= dop.communication
      %td= dop.consideration
      %td= dop.overall
      %td= dop.suggestions
      %td= dop.training
      %td= dop.time_observation
      %td= dop.time_feedback
      %td= dop.assessor
      %td= dop.assesser_GMC
      %td= dop.assessor_contact
      %td= dop.assessor_email
      %td= link_to 'Show', dop
      %td= link_to 'Edit', edit_dop_path(dop)
      %td= link_to 'Destroy', dop, :method => :delete, :data => { :confirm => 'Are you sure?' }
    

%br

= link_to 'New Dop', new_dop_path

app/views/dops/new.html.haml
%h1 New dop

= render 'form'

= link_to 'Back', dops_path

app/views/dops/show.html.haml
%p#notice= notice

%h1 DOP

%strong Curriculum Links:
%ul
  - @dop.items.each do |item|
    %li= item.code

%p
  %b Clinical setting:
  = @dop.clinical_setting
%p
  %b Problem category:
  = @dop.problem_category
%p
  %b Clinical encouter:
  = @dop.clinical_encouter
%p
  %b Complexity:
  = @dop.complexity
%p
  %b Assessor postion:
  = @dop.assessor_postion
%p
  %b Number previous assessor:
  = @dop.number_previous_assessor
%p
  %b Number previous trainee:
  = @dop.number_previous_trainee
%p
  %b Understanding:
  = @dop.understanding
%p
  %b Consent:
  = @dop.consent
%p
  %b Preparation:
  = @dop.preparation
%p
  %b Analalgesia:
  = @dop.analalgesia
%p
  %b Technical ability:
  = @dop.technical_ability
%p
  %b Aseptic:
  = @dop.aseptic
%p
  %b Seeks help:
  = @dop.seeks_help
%p
  %b Post procedure:
  = @dop.post_procedure
%p
  %b Communication:
  = @dop.communication
%p
  %b Consideration:
  = @dop.consideration
%p
  %b Overall:
  = @dop.overall
%p
  %b Suggestions:
  = @dop.suggestions
%p
  %b Training:
  = @dop.training
%p
  %b Time observation:
  = @dop.time_observation
%p
  %b Time feedback:
  = @dop.time_feedback
%p
  %b Assessor:
  = @dop.assessor
%p
  %b Assesser gmc:
  = @dop.assesser_GMC
%p
  %b Assessor contact:
  = @dop.assessor_contact
%p
  %b Assessor email:
  = @dop.assessor_email

= link_to 'Edit', edit_dop_path(@dop)
\|
= link_to 'Back', dops_path