config/routes.rb
Accs::Application.routes.draw do
  resources :items

  resources :sections

  resources :curriculums

  resources :curriculum_assessments

  resources :dops

  resources :assessments

  devise_for :users

  resources :users
  root :to => "home#index"

end

app/models/curriculum_assessment.rb
class CurriculumAssessment < ActiveRecord::Base
   attr_accessible :title, :body, :item, :dop, :dop_id, :item_id
  belongs_to :dop
  belongs_to :item
end

app/controllers/curriculum_assessments_controller.rb
class CurriculumAssessmentsController < ApplicationController
  # GET /curriculum_assessments
  # GET /curriculum_assessments.json
  def index
    @curriculum_assessments = current_user.curriculumAssessments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @curriculum_assessments }
    end
  end

  # GET /curriculum_assessments/1
  # GET /curriculum_assessments/1.json
  def show
    @curriculum_assessment = current_user.curriculumAssessments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @curriculum_assessment }
    end
  end

  # GET /curriculum_assessments/new
  # GET /curriculum_assessments/new.json
  def new
    @curriculum_assessment = CurriculumAssessment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @curriculum_assessment }
    end
  end

  # GET /curriculum_assessments/1/edit
  def edit
    @curriculum_assessment = CurriculumAssessment.find(params[:id])
  end

  # POST /curriculum_assessments
  # POST /curriculum_assessments.json
  def create
    #@curriculum_assessment = CurriculumAssessment.create(params[:curriculum_assessments])
    
    @dop = Dop.find(params[:curriculum_assessment][:dop_id])
    @item = Item.find(params[:curriculum_assessment][:item_id])
    @curriculum_assessment = CurriculumAssessment.create(item: @item, dop: @dop)


    respond_to do |format|
      if @curriculum_assessment.save
        format.html { redirect_to @curriculum_assessment, notice: 'Curriculum assessment was successfully created.' }
        format.json { render json: @curriculum_assessment, status: :created, location: @curriculum_assessment }
      else
        format.html { render action: "new" }
        format.json { render json: @curriculum_assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /curriculum_assessments/1
  # PUT /curriculum_assessments/1.json
  def update
    @curriculum_assessment = CurriculumAssessment.find(params[:id])

    respond_to do |format|
      if @curriculum_assessment.update_attributes(params[:curriculum_assessment])
        format.html { redirect_to @curriculum_assessment, notice: 'Curriculum assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @curriculum_assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculum_assessments/1
  # DELETE /curriculum_assessments/1.json
  def destroy
    @curriculum_assessment = CurriculumAssessment.find(params[:id])
    @curriculum_assessment.destroy

    respond_to do |format|
      format.html { redirect_to curriculum_assessments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/curriculum_assessments_helper.rb
module CurriculumAssessmentsHelper
end

app/views/curriculum_assessments/_form.html.haml
= simple_form_for(@curriculum_assessment) do |f|
  = f.error_notification

  .form-inputs
    =f.association :dop ,   as: :check_boxes
    =f.association :item,   as: :check_boxes



   




  .form-actions
    = f.button :submit

app/views/curriculum_assessments/edit.html.haml
%h1 Editing curriculum_assessment

= render 'form'

= link_to 'Show', @curriculum_assessment
\|
= link_to 'Back', curriculum_assessments_path

app/views/curriculum_assessments/index.html.haml
%h1 Listing curriculum_assessments

%table
  %tr
    %th
    %th
    %th

  - @curriculum_assessments.each do |curriculum_assessment|
    =curriculum_assessment.dop.consent
    
    %tr
      %td= link_to 'Show', curriculum_assessment
      %td= link_to 'Edit', edit_curriculum_assessment_path(curriculum_assessment)
      %td= link_to 'Destroy', curriculum_assessment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Curriculum assessment', new_curriculum_assessment_path

app/views/curriculum_assessments/new.html.haml
%h1 New curriculum_assessment

= render 'form'

= link_to 'Back', curriculum_assessments_path

app/views/curriculum_assessments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_curriculum_assessment_path(@curriculum_assessment)
\|
= link_to 'Back', curriculum_assessments_path